name: Close Pull Request on Create

on:
  pull_request:
    types: [opened]  # プルリクエストが作成されたときにトリガーされる

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Close pull request
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
